### ISSUE TITLE
Hello, I have a question，Motor driver library running error

### ISSUE THREAD

**Issue by h-wyj** [studica/WorldSkills-Example-Projects#1]
When you instantiate the Titan library, the compilation passes, but an error occurs at run time ，“No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again ﻿”

**Comment by h-wyj** [comment]
There was no problem before I updated the system, but after I replaced the system, other sensor libraries could run normally, but the motor drive library could not

**Comment by h-wyj** [comment]
at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:348) ﻿
﻿﻿﻿﻿﻿﻿ 	at frc.robot.Main.main(Main.java:23) ﻿
﻿﻿﻿﻿﻿﻿ # ﻿
﻿﻿﻿﻿﻿﻿ # A fatal error has been detected by the Java Runtime Environment: ﻿
﻿﻿﻿﻿﻿﻿ # ﻿
﻿﻿﻿﻿﻿﻿ #  SIGSEGV (0xb) at pc=0x761b5ca0, pid=3804, tid=3857 ﻿
﻿﻿﻿﻿﻿﻿ # ﻿
﻿﻿﻿﻿﻿﻿ # JRE version: OpenJDK Runtime Environment (11.0.7+10) (build 11.0.7+10-post-Raspbian-3deb10u1) ﻿
﻿﻿﻿﻿﻿﻿ # Java VM: OpenJDK Server VM (11.0.7+10-post-Raspbian-3deb10u1, mixed mode, concurrent mark sweep gc, linux-) ﻿
﻿﻿﻿﻿﻿﻿ # Problematic frame: ﻿
﻿﻿﻿﻿﻿﻿ # C  [libvmxpi_hal_cpp.so+0xadca0][thread 3863 also had an error] ﻿
﻿﻿﻿﻿﻿﻿ [thread 3884 also had an error] ﻿
﻿﻿﻿﻿﻿﻿   spiGoA+0x204 ﻿
﻿﻿﻿﻿﻿﻿ # ﻿
﻿﻿﻿﻿﻿﻿ # No core dump will be written. Core dumps have been disabled. To enable core dumping, try "ulimit -c unlimited" before starting Java again ﻿
﻿﻿﻿﻿﻿﻿ # ﻿

**Comment by Jm-Taylor** [comment]
This is the Java JRE crashing on the VMX. I would need the full error message to debug. You only put part of it 

`at edu.wpi.first.wpilibj.RobotBase.startRobot(RobotBase.java:348) ﻿`

**Comment by h-wyj** [comment]
![1](https://user-images.githubusercontent.com/70889165/123354317-fa3bd280-d595-11eb-98cf-db379c98dfd9.png)

**Comment by h-wyj** [comment]
![8](https://user-images.githubusercontent.com/70889165/123354424-33744280-d596-11eb-9f1d-01ad5cd98b83.png)

**Comment by h-wyj** [comment]
![9](https://user-images.githubusercontent.com/70889165/123354472-4be45d00-d596-11eb-82f4-7840a138da27.png)

**Comment by Jm-Taylor** [comment]
It looks like it's trying to load Athena objects which is the wrong target. Is your build.gradle setup correctly to point at the VMX and not the roboRIO?

Can you also verify which version of the Studica.json you have?

**Comment by h-wyj** [comment]
I have used VMX-WSR to set the file to VMX and VMX-PI to set the file to VMX-PI but the same error occurs in both cases

**Comment by h-wyj** [comment]
Hello, is there any file missing in my Raspberry Pi?  Because it can be used again when I did not update the system before, but the program reported an error after the system was updated

**Comment by h-wyj** [comment]
![3](https://user-images.githubusercontent.com/70889165/123496148-5582c900-d659-11eb-8ea5-f4fdb407b6f4.png)

**Comment by h-wyj** [comment]
When the program reported an error, I tried to change the system back to the original, but the program still reported an error

**Comment by h-wyj** [comment]
I thought it was my computer, so I changed two computers and nothing worked out

**Comment by h-wyj** [comment]
C ++ programs will work fine, Java compilation will pass, but the runtime will report an error

**Comment by h-wyj** [comment]
Thank you.  The problem has been solved.  I've been bothering you these days
